<%@page import="java.util.ArrayList"%>
<%@page import="java.time.Instant"%>
<%@page import="java.util.Date"%>
<%@page import="classes.Vendor"%>
<%@page import="org.joda.time.LocalDate"%>
<%@page import="java.util.List"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

        <title> Attendance Report For a Period </title>

        <!-- Bootstrap Core CSS -->
        <link href="../../static/css/bootstrap.min.css" rel="stylesheet">

        <style>
            body{
                font-family: serif;
            }
            .panel-default > .panel-heading {
                background-color:white;
            }

            table { 
                table-layout: fixed; 
            }
            table th, table td { 
                overflow: hidden; 
            }
            #subHead{
                text-decoration: underline; 
                margin-top: 20px; 
                margin-bottom: 20px; 
                font-style: italic; 
                font-size: large;
            }
        </style>

    </head>

    <body>

        <%
            List<LocalDate> dayList = new ArrayList();

            dayList = (List<LocalDate>) session.getAttribute("dayList");
            Vendor vendor = (Vendor) session.getAttribute("vendor");

            //matket day
            String day = (String) session.getAttribute("day");
            //admin
            String username = (String) session.getAttribute("User");
            //start date
            String startDate = (String) session.getAttribute("startDate");
            //end date
            String endDate = (String) session.getAttribute("endDate");
            //today
            LocalDate currentDate = LocalDate.now();
            int weekNumber = 0, start = 0, totalNoOfAttend = 0;
            int noOfColumns = dayList.size();
        %>

        <br/>

        <section>
            <div class="container">
                <div class="panel panel-default">

                    <div class="panel-heading">
                        <!-- start of report header -->
                        <div class="row">
                            <div class="col-sm-12">
                                <!-- logo -->
                                <div class="col-xs-2">
                                    <img src="../../static/images/logo.png">
                                </div>
                                <!-- topic of the report -->
                                <div class="col-sm-7">
                                    <h1 style="text-align: center;"> Vendor Attendance Report </h1>
                                </div>
                                <!--download and back buttons-->
                                <div class="col-sm-3">
                                    <button class="btn btn-primary hidden-print" onClick="window.print();">Download report</button>
                                    <a href="../reportViewAttendanceTimePeriod.jsp"><button class="btn btn-primary hidden-print" >Back</button></a>

                                </div>
                            </div>
                        </div>
                        <!--sub topic-->
                        <div class="row">
                            <div class="col-sm-12">
                                <h3 style="text-align: center;"> (Attendance Report of <%out.println(vendor.getVendorName());%> from <% out.println(startDate); %> to <% out.println(endDate);%>) </h3>
                            </div>
                        </div>
                            <!-- report generation details date and admin -->
                        <div class="row">
                            <div class="col-sm-12">
                                <h4 id="left" style="float: left; margin-left: 10px;"> Generated By : <% out.println(username); %>  </h4>
                                <h4 id="right" style="float: right; margin-right: 10px;"> Generated Date : <% out.println(currentDate);%> </h4>
                            </div>
                        </div>
                            


                        <hr>
                        <div class="panel-body">
                            <!-- sub topic according to market day -->

                            <% if (day.equals("TH")) { %>

                            <h3 style="font-weight: bold; font-style: oblique;"> Attendance on Thursday Market </h3>

                            <% } else { %>

                            <h3 style="font-weight: bold; font-style: oblique;"> Attendance on Saturday Market </h3>

                            <% } %>

                             <!-- content table -->
                            <div class="col-xs-12">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 15%;"> Attendance Status </th>
                                                <%
                                                    start = weekNumber;
                                                    for (LocalDate d : dayList) {
                                                        weekNumber += 1;
                                                %>
                                            <th style="width: 5%; font-size: 12px;"> <% out.println(d); %> </th>
                                                <%
                                                    }
                                                %> 
                                        </tr>
                                    </thead>

                                    <tbody>

                                        <tr>
                                            <td> Attend </td>

                                            <%
                                                String attendance[];

                                                if (day.equals("TH")) {
                                                    attendance = vendor.getAttendancePeriodThursday();
                                                } else {
                                                    attendance = vendor.getAttendancePeriodSaturday();
                                                }

                                                for (int i = start; i < weekNumber; i++) {
                                                    if (attendance[i].equals("1")) {
                                                        totalNoOfAttend += 1;
                                            %>

                                            <td align="center"> <%out.println("<span class='glyphicon glyphicon-ok' style=''></span>");%> </td>

                                            <% } else { %>

                                            <td align="center"> <% out.println("<span style='font-size:25px;'>-</span>");%> </td>

                                            <%
                                                    }
                                                }
                                            %>

                                        </tr>

                                    </tbody>
                                </table> 
                            </div>

                            No.of weeks market held : <% out.println(weekNumber); %> <br/>
                            No.of weeks attend : <% out.println(totalNoOfAttend);%> <br/> <br/>

                            <label> <i> This is an auto generated report from MartRunner. </i> </label>

                        </div>
                    </div>
                </div> 
        </section>

        <!-- jQuery -->
        <script src="../static/js/jquery.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="../static/js/bootstrap.min.js"></script>

    </body>
</html>
