<%@page import="classes.BlacklistVendors"%>
<%@page import="org.joda.time.LocalDate"%>
<%@page import="java.util.ArrayList"%>
<%@page import="java.util.List"%>
<%@page import="classes.Vendor"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>BlackListed Vendors | Reports| MartRunner</title>
        
        <!-- Bootstrap Core CSS -->
        <link href="../../static/css/bootstrap.min.css" rel="stylesheet">

        <style>
            body{
                font-family: serif;
                font-size: 18px;
            }
            .panel-default > .panel-heading {
                background-color:white;
            }
        </style>
    </head>
    
    <body>

        <%
            List<BlacklistVendors> vendorList = new ArrayList();
            
            //admin
            String username = (String) session.getAttribute("User");

            if (session.getAttribute("vendorList") != null) {
                vendorList = (List<BlacklistVendors>) session.getAttribute("vendorList");
            }

            //today
            LocalDate currentDate = LocalDate.now();
        %>

        <br/>

        <section>
            <div class="container">
                <div class="panel panel-default">

                    <div class="panel-heading">
                        <!-- start of report header -->
                        <div class="row">
                            <div class="col-sm-12">
                                <!-- logo -->
                                <div class="col-xs-2">
                                    <img src="../../static/images/logo.png">
                                </div>
                                <!-- topic of the report -->
                                <div class="col-sm-7">
                                    <h1 style="text-align: center;"> Black Listed Vendor List </h1>
                                </div>
                                <!--download and back buttons-->
                                <div class="col-sm-3">
                                    <button class="btn btn-primary hidden-print" onClick="window.print();">Download report</button>
                                    <a href="../adminHomePage.jsp"><button class="btn btn-primary hidden-print" >Back</button></a>

                                </div>
                            </div>

                            <!-- report generation details date and admin -->
                            <div class="row">
                                <div class="col-sm-12">
                                    <h4 id="left" style="float: left; margin-left: 10px;"> Generated By : <% out.println(username); %>  </h4>
                                    <h4 id="right" style="float: right; margin-right: 10px;"> Generated Date : <% out.println(currentDate);%> </h4>
                                </div>
                            </div>
                            <hr>

                            <!-- topic -->
                            <h3 style="font-weight: bold; font-style: oblique; margin-left: 5px;"> Blacklisted Vendors</h3>

                            <!-- content table -->
                            <div class="col-xs-12">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 10%; font-size: 18px;"> Vendor Name </th>
                                            <th style="width: 10%; font-size: 18px;"> Reason </th>
                                            <th style="width: 10%; font-size: 18px;"> Black Listed Date </th>
                                        </tr>
                                    </thead>

                                    <tbody>

                                        <%
                                            for (BlacklistVendors v : vendorList) {
                                        %>
                                        <tr>

                                            <td> <% out.println(v.getVendorName()); %> </td>
                                            <td> <% out.println(v.getBlackListReason()); %> </td>
                                            <td> <% out.println(v.getBlacklistDate()); %> </td>

                                        </tr>
                                        <%}%>
                                    </tbody>
                                </table>
                            </div>

                            <label> <i> This is an auto generated report from MartRunner. </i> </label>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- jQuery -->
        <script src="../../static/js/jquery.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="../../static/js/bootstrap.min.js"></script>

    </body>
</html>
