<%@page import="java.util.ArrayList"%>
<%@page import="java.time.Instant"%>
<%@page import="java.util.Date"%>
<%@page import="classes.Vendor"%>
<%@page import="org.joda.time.LocalDate"%>
<%@page import="java.util.List"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title> Full Year Attendance Report </title>

        <!-- Bootstrap Core CSS -->
        <link href="../../static/css/bootstrap.min.css" rel="stylesheet">

        <style>
            body{
                font-family: serif;
            }
            .panel-default > .panel-heading {
                background-color:white;
            }

            table { 
                table-layout: fixed; 
            }
            table th, table td { 
                overflow: hidden; 
            }
            #subHead{
                text-decoration: underline; 
                margin-top: 20px; 
                margin-bottom: 20px; 
                font-style: italic; 
                font-size: large;
            }
        </style>

    </head>

    <body>

        <%
            List<LocalDate> thursdays = new ArrayList();
            List<LocalDate> saturdays = new ArrayList();
            List<Vendor> attendanceListTh = new ArrayList();
            List<Vendor> attendanceListSa = new ArrayList();

            thursdays = (List<LocalDate>) session.getAttribute("dayListThursday");
            saturdays = (List<LocalDate>) session.getAttribute("dayListSaturday");

            attendanceListTh = (List<Vendor>) session.getAttribute("thursdayVendorAttendanceList");
            attendanceListSa = (List<Vendor>) session.getAttribute("saturdayVendorAttendanceList");

            //year
            int year = (Integer) session.getAttribute("year");
            //admin
            String username = (String) session.getAttribute("User");
            //today
            LocalDate currentDate = LocalDate.now();
            int weekNumberTh = 0, startTh = 0, weekNumberSa = 0, startSa = 0;
        %>

        <br/>

        <section>
            <div class="container">
                <div class="panel panel-default">

                    <div class="panel-heading">
                        <!-- start of report header -->
                        <div class="row">
                            <div class="col-sm-12">
                                <!-- logo -->
                                <div class="col-xs-2">
                                    <img src="../../static/images/logo.png">
                                </div>
                                <!-- topic of the report -->
                                <div class="col-sm-7">
                                    <h1 style="text-align: center;"> Vendor Attendance Report </h1>
                                </div>
                                <!--download and back buttons-->
                                <div class="col-sm-3">
                                    <button class="btn btn-primary hidden-print" onClick="window.print();">Download report</button>
                                    <a href="../reportViewAttendanceFullYear.jsp"><button class="btn btn-primary hidden-print" >Back</button></a>

                                </div>
                            </div>
                            <!--sub topic-->
                            <div class="row">
                                <div class="col-sm-12">
                                    <h3 style="text-align: center;"> (Attendance Report of year <% out.println(year);%>) </h3>
                                </div>
                            </div>

                            <!-- report generation details date and admin -->
                            <div class="row">
                                <div class="col-sm-12">
                                    <h4 id="left" style="float: left; margin-left: 10px;"> Generated By : <% out.println(username); %>  </h4>
                                    <h4 id="right" style="float: right; margin-right: 10px;"> Generated Date : <% out.println(currentDate);%> </h4>
                                </div>
                            </div>
                        </div>                   
                        <hr>
                        <div class="panel-body">

                            <!-- Thursay Panel -->    

                            <h3 style="font-weight: bold; font-style: oblique;"> Vendor Attendance of Thursday Market </h3>

                            <!-- results for  January, February, March - thursday-->
                            <h5 id="subHead"> Month of January, February, March </h5>

                            <div class="col-xs-12">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 15%;"> Vendor Name </th>
                                                <%
                                                    startTh = weekNumberTh;
                                                    for (LocalDate d : thursdays) {
                                                        String date = String.valueOf(d);
                                                        if (date.substring(5, 7).equals("01") || date.substring(5, 7).equals("02") || date.substring(5, 7).equals("03")) {
                                                            weekNumberTh += 1;
                                                %>
                                            <th style="width: 5%; font-size: 12px;"> <% out.println(d); %> </th>
                                                <%
                                                        }
                                                    }
                                                %> 
                                        </tr>
                                    </thead>

                                    <tbody>
                                        <%
                                            for (Vendor v : attendanceListTh) {
                                        %>
                                        <tr>
                                            <td> <% out.println(v.getVendorName()); %> </td>

                                            <%
                                                String attendance[] = v.getAttendancePeriodThursday();
                                                for (int i = startTh; i < weekNumberTh; i++) {
                                            %>
                                            <td align="center"> <% if (attendance[i].equals("1")) {
                                                    out.println("<span class='glyphicon glyphicon-ok' style=''></span>");
                                                } else {
                                                    out.println("<span style='font-size:25px;'>-</span>");
                                                }
                                                %> 
                                            </td>
                                            <%
                                                }
                                            %>

                                        </tr>
                                        <%
                                            }
                                        %>
                                    </tbody>
                                </table> 
                            </div>

                            <%
                                String lastDate = String.valueOf(thursdays.get(thursdays.size() - 1));
                                if (Integer.parseInt(lastDate.substring(5, 7)) > 3) {
                            %>        

                            <!-- results for  April, May, June - thursday-->
                            <h5 id="subHead"> Month of April, May, June </h5>

                            <div class="col-xs-12">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 15%;"> Vendor Name </th>
                                                <%
                                                    startTh = weekNumberTh;
                                                    for (LocalDate d : thursdays) {
                                                        String date = String.valueOf(d);
                                                        if (date.substring(5, 7).equals("04") || date.substring(5, 7).equals("05") || date.substring(5, 7).equals("06")) {
                                                            weekNumberTh += 1;
                                                %>
                                            <th style="width: 5%; font-size: 12px;"> <% out.println(d); %> </th>
                                                <%
                                                        }
                                                    }
                                                %> 
                                        </tr>
                                    </thead>

                                    <tbody>
                                        <%
                                            for (Vendor v : attendanceListTh) {
                                        %>
                                        <tr>
                                            <td> <% out.println(v.getVendorName()); %> </td>

                                            <%
                                                String attendance[] = v.getAttendancePeriodThursday();

                                                for (int i = startTh; i < weekNumberTh; i++) {
                                            %>
                                            <td align="center"> <% if (attendance[i].equals("1")) {
                                                    out.println("<span class='glyphicon glyphicon-ok' style=''></span>");
                                                } else {
                                                    out.println("<span style='font-size:25px;'>-</span>");
                                                }
                                                %> 
                                            </td>
                                            <%
                                                }
                                            %>

                                        </tr>
                                        <%
                                            }
                                        %>
                                    </tbody>
                                </table> 
                            </div>
                            <%
                                }

                                if (Integer.parseInt(lastDate.substring(5, 7)) > 6) {
                            %>        

                            <!-- results for July, August, September - thursday-->
                            <h5 id="subHead"> Month of July, August, September </h5>

                            <div class="col-xs-12">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 15%;"> Vendor Name </th>
                                                <%
                                                    startTh = weekNumberTh;
                                                    for (LocalDate d : thursdays) {
                                                        String date = String.valueOf(d);
                                                        if (date.substring(5, 7).equals("07") || date.substring(5, 7).equals("08") || date.substring(5, 7).equals("09")) {
                                                            weekNumberTh += 1;
                                                %>
                                            <th style="width: 5%; font-size: 12px;"> <% out.println(d); %> </th>
                                                <%
                                                        }
                                                    }
                                                %> 
                                        </tr>
                                    </thead>

                                    <tbody>
                                        <%
                                            for (Vendor v : attendanceListTh) {
                                        %>
                                        <tr>
                                            <td> <% out.println(v.getVendorName()); %> </td>

                                            <%
                                                String attendance[] = v.getAttendancePeriodThursday();

                                                for (int i = startTh; i < weekNumberTh; i++) {
                                            %>
                                            <td align="center"> <% if (attendance[i].equals("1")) {
                                                    out.println("<span class='glyphicon glyphicon-ok' style=''></span>");
                                                } else {
                                                    out.println("<span style='font-size:25px;'>-</span>");
                                                }
                                                %> 
                                            </td>
                                            <%
                                                }
                                            %>

                                        </tr>
                                        <%
                                            }
                                        %>
                                    </tbody>
                                </table> 
                            </div>
                            <%
                                }

                                if (Integer.parseInt(lastDate.substring(5, 7)) > 9) {
                            %>        

                            <!-- results for October, November, December - thursday-->
                            <h5 id="subHead"> Month of October, November, December </h5>

                            <div class="col-xs-12">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 15%;"> Vendor Name </th>
                                                <%
                                                    startTh = weekNumberTh;
                                                    for (LocalDate d : thursdays) {
                                                        String date = String.valueOf(d);
                                                        if (date.substring(5, 7).equals("10") || date.substring(5, 7).equals("11") || date.substring(5, 7).equals("12")) {
                                                            weekNumberTh += 1;
                                                %>
                                            <th style="width: 5%; font-size: 12px;"> <% out.println(d); %> </th>
                                                <%
                                                        }
                                                    }
                                                %> 
                                        </tr>
                                    </thead>

                                    <tbody>
                                        <%
                                            for (Vendor v : attendanceListTh) {
                                        %>
                                        <tr>
                                            <td> <% out.println(v.getVendorName()); %> </td>

                                            <%
                                                String attendance[] = v.getAttendancePeriodThursday();
                                                for (int i = startTh; i < weekNumberTh; i++) {
                                            %>
                                            <td align="center"> <% if (attendance[i].equals("1")) {
                                                    out.println("<span class='glyphicon glyphicon-ok' style=''></span>");
                                                } else {
                                                    out.println("<span style='font-size:25px;'>-</span>");
                                                }
                                                %> 
                                            </td>
                                            <%
                                                }
                                            %>

                                        </tr>
                                        <%
                                            }
                                        %>
                                    </tbody>
                                </table> 
                            </div>

                            <%
                                }
                            %>

                            <!-- start of saturday attendance tables -->

                            <h3 style="font-weight: bold; font-style: oblique;"> Vendor Attendance of Saturday Market </h3>

                            <!-- results for  January, February, March - Saturday-->
                            <h5 id="subHead"> Month of January, February, March </h5>

                            <div class="col-xs-12">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 15%;"> Vendor Name </th>
                                                <%
                                                    startSa = weekNumberSa;
                                                    for (LocalDate d : saturdays) {
                                                        String date = String.valueOf(d);
                                                        if (date.substring(5, 7).equals("01") || date.substring(5, 7).equals("02") || date.substring(5, 7).equals("03")) {
                                                            weekNumberSa += 1;
                                                %>
                                            <th style="width: 5%; font-size: 12px;"> <% out.println(d); %> </th>
                                                <%
                                                        }
                                                    }
                                                %> 
                                        </tr>
                                    </thead>

                                    <tbody>
                                        <%
                                            for (Vendor v : attendanceListSa) {
                                        %>
                                        <tr>
                                            <td> <% out.println(v.getVendorName()); %> </td>

                                            <%
                                                String attendance[] = v.getAttendancePeriodSaturday();
                                                for (int i = startSa; i < weekNumberSa; i++) {
                                            %>
                                            <td align="center"> <% if (attendance[i].equals("1")) {
                                                    out.println("<span class='glyphicon glyphicon-ok' style=''></span>");
                                                } else {
                                                    out.println("<span style='font-size:25px;'>-</span>");
                                                }
                                                %> 
                                            </td>
                                            <%
                                                }
                                            %>

                                        </tr>
                                        <%
                                            }
                                        %>
                                    </tbody>
                                </table> 
                            </div>

                            <%
                                lastDate = String.valueOf(saturdays.get(saturdays.size() - 1));
                                if (Integer.parseInt(lastDate.substring(5, 7)) > 3) {
                            %>        

                            <!-- results for  April, May, June - Saturday-->
                            <h5 id="subHead"> Month of April, May, June </h5>

                            <div class="col-xs-12">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 15%;"> Vendor Name </th>
                                                <%
                                                    startSa = weekNumberSa;
                                                    for (LocalDate d : saturdays) {
                                                        String date = String.valueOf(d);
                                                        if (date.substring(5, 7).equals("04") || date.substring(5, 7).equals("05") || date.substring(5, 7).equals("06")) {
                                                            weekNumberSa += 1;
                                                %>
                                            <th style="width: 5%; font-size: 12px;"> <% out.println(d); %> </th>
                                                <%
                                                        }
                                                    }
                                                %> 
                                        </tr>
                                    </thead>

                                    <tbody>
                                        <%
                                            for (Vendor v : attendanceListSa) {
                                        %>
                                        <tr>
                                            <td> <% out.println(v.getVendorName()); %> </td>

                                            <%
                                                String attendance[] = v.getAttendancePeriodSaturday();

                                                for (int i = startSa; i < weekNumberSa; i++) {
                                            %>
                                            <td align="center"> <% if (attendance[i].equals("1")) {
                                                    out.println("<span class='glyphicon glyphicon-ok' style=''></span>");
                                                } else {
                                                    out.println("<span style='font-size:25px;'>-</span>");
                                                }
                                                %> 
                                            </td>
                                            <%
                                                }
                                            %>

                                        </tr>
                                        <%
                                            }
                                        %>
                                    </tbody>
                                </table> 
                            </div>
                            <%
                                }

                                if (Integer.parseInt(lastDate.substring(5, 7)) > 6) {
                            %>        

                            <!-- results for  July, August, September - Saturday-->
                            <h5 id="subHead"> Month of July, August, September </h5>

                            <div class="col-xs-12">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 15%;"> Vendor Name </th>
                                                <%
                                                    startSa = weekNumberSa;
                                                    for (LocalDate d : saturdays) {
                                                        String date = String.valueOf(d);
                                                        if (date.substring(5, 7).equals("07") || date.substring(5, 7).equals("08") || date.substring(5, 7).equals("09")) {
                                                            weekNumberSa += 1;
                                                %>
                                            <th style="width: 5%; font-size: 12px;"> <% out.println(d); %> </th>
                                                <%
                                                        }
                                                    }
                                                %> 
                                        </tr>
                                    </thead>

                                    <tbody>
                                        <%
                                            for (Vendor v : attendanceListSa) {
                                        %>
                                        <tr>
                                            <td> <% out.println(v.getVendorName()); %> </td>

                                            <%
                                                String attendance[] = v.getAttendancePeriodSaturday();

                                                for (int i = startSa; i < weekNumberSa; i++) {
                                            %>
                                            <td align="center"> <% if (attendance[i].equals("1")) {
                                                    out.println("<span class='glyphicon glyphicon-ok' style=''></span>");
                                                } else {
                                                    out.println("<span style='font-size:25px;'>-</span>");
                                                }
                                                %> 
                                            </td>
                                            <%
                                                }
                                            %>

                                        </tr>
                                        <%
                                            }
                                        %>
                                    </tbody>
                                </table> 
                            </div>
                            <%
                                }

                                if (Integer.parseInt(lastDate.substring(5, 7)) > 9) {
                            %>        


                            <!-- results for  October, November, December - Saturday-->
                            <h5 id="subHead"> Month of October, November, December </h5>

                            <div class="col-xs-12">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 15%;"> Vendor Name </th>
                                                <%
                                                    startSa = weekNumberSa;
                                                    for (LocalDate d : saturdays) {
                                                        String date = String.valueOf(d);
                                                        if (date.substring(5, 7).equals("10") || date.substring(5, 7).equals("11") || date.substring(5, 7).equals("12")) {
                                                            weekNumberSa += 1;
                                                %>
                                            <th style="width: 5%; font-size: 12px;"> <% out.println(d); %> </th>
                                                <%
                                                        }
                                                    }
                                                %> 
                                        </tr>
                                    </thead>

                                    <tbody>
                                        <%
                                            for (Vendor v : attendanceListSa) {
                                        %>
                                        <tr>
                                            <td> <% out.println(v.getVendorName()); %> </td>

                                            <%
                                                String attendance[] = v.getAttendancePeriodSaturday();

                                                for (int i = startSa; i < weekNumberSa; i++) {
                                            %>
                                            <td align="center"> <% if (attendance[i].equals("1")) {
                                                    out.println("<span class='glyphicon glyphicon-ok' style=''></span>");
                                                } else {
                                                    out.println("<span style='font-size:25px;'>-</span>");
                                                }
                                                %> 
                                            </td>
                                                <%
                                                    }
                                                %>

                                        </tr>
                                        <%
                                            }
                                        %>
                                    </tbody>
                                </table> 
                            </div>

                            <%
                                }
                            %>

                            <label> <i> This is an auto generated report from MartRunner. </i> </label>

                        </div>
                    </div>
                    </section>

                    <!-- jQuery -->
                    <script src="../static/js/jquery.js"></script>

                    <!-- Bootstrap Core JavaScript -->
                    <script src="../static/js/bootstrap.min.js"></script>

                    </body>
                    </html>
